### PR TITLE
Added Linux Payloads

### PR DESCRIPTION
**Pull request by harsha-0110**
Added Linux Loader payloads by EchoStrech for PS4 11.00 fw

### CODE REVIEW

**Comment by 0x1iii1ii** [comment]
Have you tested it yet? I don't have ps4 atm

**Comment by 0x1iii1ii** [comment]
check and merged thank you!

**Comment by kmeps4** [comment]
Pls don't forget original Linux Mod.. Proper credit should go to: https://github.com/ps4boot/ps4-linuxpayloads and PSXIta Team

**Comment by 0x1iii1ii** [comment]
> Pls don't forget original Linux Mod.. Proper credit should go to: https://github.com/ps4boot/ps4-linuxpayloads and PSXIta Team

thanks, @kmeps4 for pointing out the owner of the release. Added and properly credited at the release page.

**Pull request merged**
